FROM w251/cuda:dev-tx2-4.2_b158


RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN pip install paho-mqtt

RUN pip install jupyter
RUN pip install numpy
VOLUME /notebook
WORKDIR /notebook
EXPOSE 8888

#ENV KERAS_BACKEND=theano

#  CMD jupyter notebook --no-browser --ip=0.0.0.0 --NotebookApp.token= --allow-root
CMD jupyter notebook --no-browser --ip=0.0.0.0 --allow-root
